services:
  test_db:
    image: postgres:14-alpine
    env_file: .env.test
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - test_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  test-runner:
    build: .
    command: ["python", "-m", "pytest"]
    volumes:
      - .:/app
    env_file:
      - .env.test
    depends_on:
      test_db:
        condition: service_healthy

volumes:
  test_postgres_data:
